// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIC-jsGmKkrzKV0o4qTMO6mSxfaRveidI',
    appId: '1:291539753983:web:4b39a89b3c340e6e6025ca',
    messagingSenderId: '291539753983',
    projectId: 'chat-app-720fb',
    authDomain: 'chat-app-720fb.firebaseapp.com',
    storageBucket: 'chat-app-720fb.appspot.com',
    measurementId: 'G-JXBDSZS69L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfLTDv-CvJZMFTFwDD8OPhB_j1GrpItNg',
    appId: '1:291539753983:android:8b5a599be6079a4a6025ca',
    messagingSenderId: '291539753983',
    projectId: 'chat-app-720fb',
    storageBucket: 'chat-app-720fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBth1uRR9OYJCEQsYB9JdjWFXJYxdUPnjM',
    appId: '1:291539753983:ios:00a16257a551b5cf6025ca',
    messagingSenderId: '291539753983',
    projectId: 'chat-app-720fb',
    storageBucket: 'chat-app-720fb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBth1uRR9OYJCEQsYB9JdjWFXJYxdUPnjM',
    appId: '1:291539753983:ios:5bceeec2ac1def7d6025ca',
    messagingSenderId: '291539753983',
    projectId: 'chat-app-720fb',
    storageBucket: 'chat-app-720fb.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
